//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostsWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HostsWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon _125 {
            get {
                object obj = ResourceManager.GetObject("_125", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _312 {
            get {
                object obj = ResourceManager.GetObject("_312", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _330 {
            get {
                object obj = ResourceManager.GetObject("_330", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _340 {
            get {
                object obj = ResourceManager.GetObject("_340", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon blaster {
            get {
                object obj = ResourceManager.GetObject("blaster", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_01 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_02 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_03 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_04 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_05 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_06 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_07 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_08 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_09 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_10 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_11 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_12 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_13 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_14 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_15 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_16 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_17 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_18 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_19 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_20 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_21 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_22 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_23 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_24 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus48x48_25 {
            get {
                object obj = ResourceManager.GetObject("bonus48x48_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon categories {
            get {
                object obj = ResourceManager.GetObject("categories", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon hacks {
            get {
                object obj = ResourceManager.GetObject("hacks", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] hsw {
            get {
                object obj = ResourceManager.GetObject("hsw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_01 {
            get {
                object obj = ResourceManager.GetObject("onebit_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_02 {
            get {
                object obj = ResourceManager.GetObject("onebit_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_03 {
            get {
                object obj = ResourceManager.GetObject("onebit_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_04 {
            get {
                object obj = ResourceManager.GetObject("onebit_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_05 {
            get {
                object obj = ResourceManager.GetObject("onebit_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_06 {
            get {
                object obj = ResourceManager.GetObject("onebit_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_07 {
            get {
                object obj = ResourceManager.GetObject("onebit_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_08 {
            get {
                object obj = ResourceManager.GetObject("onebit_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_09 {
            get {
                object obj = ResourceManager.GetObject("onebit_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_10 {
            get {
                object obj = ResourceManager.GetObject("onebit_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_11 {
            get {
                object obj = ResourceManager.GetObject("onebit_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_12 {
            get {
                object obj = ResourceManager.GetObject("onebit_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_13 {
            get {
                object obj = ResourceManager.GetObject("onebit_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_14 {
            get {
                object obj = ResourceManager.GetObject("onebit_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_15 {
            get {
                object obj = ResourceManager.GetObject("onebit_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_16 {
            get {
                object obj = ResourceManager.GetObject("onebit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_17 {
            get {
                object obj = ResourceManager.GetObject("onebit_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_18 {
            get {
                object obj = ResourceManager.GetObject("onebit_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_19 {
            get {
                object obj = ResourceManager.GetObject("onebit_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_20 {
            get {
                object obj = ResourceManager.GetObject("onebit_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_21 {
            get {
                object obj = ResourceManager.GetObject("onebit_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_22 {
            get {
                object obj = ResourceManager.GetObject("onebit_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_23 {
            get {
                object obj = ResourceManager.GetObject("onebit_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_24 {
            get {
                object obj = ResourceManager.GetObject("onebit_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_25 {
            get {
                object obj = ResourceManager.GetObject("onebit_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_26 {
            get {
                object obj = ResourceManager.GetObject("onebit_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_27 {
            get {
                object obj = ResourceManager.GetObject("onebit_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_28 {
            get {
                object obj = ResourceManager.GetObject("onebit_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_29 {
            get {
                object obj = ResourceManager.GetObject("onebit_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_30 {
            get {
                object obj = ResourceManager.GetObject("onebit_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_31 {
            get {
                object obj = ResourceManager.GetObject("onebit_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_32 {
            get {
                object obj = ResourceManager.GetObject("onebit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_33 {
            get {
                object obj = ResourceManager.GetObject("onebit_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_34 {
            get {
                object obj = ResourceManager.GetObject("onebit_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_35 {
            get {
                object obj = ResourceManager.GetObject("onebit_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_36 {
            get {
                object obj = ResourceManager.GetObject("onebit_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_37 {
            get {
                object obj = ResourceManager.GetObject("onebit_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_38 {
            get {
                object obj = ResourceManager.GetObject("onebit_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_39 {
            get {
                object obj = ResourceManager.GetObject("onebit_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_40 {
            get {
                object obj = ResourceManager.GetObject("onebit_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_41 {
            get {
                object obj = ResourceManager.GetObject("onebit_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_42 {
            get {
                object obj = ResourceManager.GetObject("onebit_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_43 {
            get {
                object obj = ResourceManager.GetObject("onebit_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_44 {
            get {
                object obj = ResourceManager.GetObject("onebit_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_45 {
            get {
                object obj = ResourceManager.GetObject("onebit_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_46 {
            get {
                object obj = ResourceManager.GetObject("onebit_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_47 {
            get {
                object obj = ResourceManager.GetObject("onebit_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_48 {
            get {
                object obj = ResourceManager.GetObject("onebit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_49 {
            get {
                object obj = ResourceManager.GetObject("onebit_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap onebit_50 {
            get {
                object obj = ResourceManager.GetObject("onebit_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon thunder3a {
            get {
                object obj = ResourceManager.GetObject("thunder3a", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
